name = "Regress"
uuid = "0ccf13ad-a1f2-44b4-972b-15ef40764d74"
version = "0.1.0"

[deps]
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FixedEffects = "c8885935-8500-56a7-9867-7708b20db0eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"

[sources]
FixedEffects = {rev = "master", url = "https://github.com/gragusa/FixedEffects.jl"}

[extensions]
RegressLVExt = "LoopVectorization"

[compat]
CSV = "0.8, 0.9, 0.10"
CUDA = "5"
CategoricalArrays = "0.10, 1"
CovarianceMatrices = "0.30"
DataFrames = "0.21, 0.22, 1"
FixedEffects = "2.4.1"
LinearAlgebra = "1.10"
LoopVectorization = "0.12"
Metal = "1"
PrecompileTools = "1"
Printf = "1.10"
Reexport = "0.1, 0.2, 1"
StableRNGs = "1.0.4"
Statistics = "1.10, 1.11"
StatsAPI = "1"
StatsBase = "0.33, 0.34"
StatsFuns = "0.9, 1"
StatsModels = "0.7"
Tables = "1"
Test = "1.10"
julia = "1.10"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CategoricalArrays", "CSV", "CUDA", "Metal", "StableRNGs", "StatsBase", "Test"]
